#include "lang.h"

QMap<QString, QString> texts_en = {
    {"BTN_SAVE", "Save"},
    {"BTN_DIS", "Discard"},
    {"BTN_CAN", "Cancel"},
    {"BTN_ADD", "Add"},
    {"BTN_APP", "Apply"},
    {"BTN_RES", "Reset"},
    {"BTN_YES", "Yes"},
    {"BTN_NO", "No"},
    {"TTL_INC", "INCOME LIST"},
    {"TTL_EXP", "EXPENSE LIST"},
    {"INC", "Income"},
    {"EXP", "Expenses"},
    {"AM", "Amount"},
    {"ITV", "Interval"},
    {"DES", "Description"},
    {"CB_MTH", "Show only monthly"},
    {"INC_SUM", "Income sum:"},
    {"EXP_SUM", "Expense sum:"},
    {"PRF_SUM", "Total sum:"},
    {"MENU_MENU", "Menu"},
    {"MENU_DATA", "File"},
    {"MENU_ABOUT", "About"},
    {"ACT_OPEN_SET", "Open settings..."},
    {"ACT_OPEN_CON", "Open configuration..."},
    {"ACT_SAVE_ALL", "Save all"},
    {"ACT_LOAD_BU", "Load backup..."},
    {"ACT_ABOUT", "About"},
    {"SW_TTL", "Settings"},
    {"SW_LAN", "Language:"},
    {"SW_CUR", "Currency:"},
    {"SW_DAT", "Date format:"},
    {"SW_DATA_FP", "Data file path"},
    {"SW_DATA_TTL", "Open file..."},
    {"SW_CD", "Confirm delete"},
    {"SW_EAS", "Auto save"},
    {"SW_BOAE", "Backup on app exit"},
    {"SW_MXB", "Max. backups:"},
    {"SW_ERASE", "Erase data"},
    {"SW_DT", "Developer tools"},
    {"SW_EL", "Logging"},
    {"SW_VER", "Application version"},
    {"CW_EXP", "Expenses"},
    {"CW_INC", "Income"},
    {"CW_TTL", "Configuration window"},
    {"CW_LAST_SAVE", "Last saved on"},
    {"EW_TTL", "Entry window"},
    {"EW_SPBX_SUF", " months"},
    {"EW_CMBX_MTH", "Monthly"},
    {"EW_CMBX_QRT", "Quarterly"},
    {"EW_CMBX_YR", "Yearly"},
    {"EW_CMBX_ONT", "One-time"},
    {"EW_CMBX_OTH", "Other"},
    {"EW_CMBX_OTH_TEXT", "Every %1 months"},
    {"EW_ADD_TO", "Add to:"},
    {"EW_EDIT", "Edit"},
    {"EW_ERR_TTL", "Invalid!"},
    {"EW_ERR_ICR", "Incorrect format"},
    {"EW_ERR_EMT", "Input cannot be empty"},
    {"INFO_TTL", "Information about Finance Manager"},
    {"INFO_TTL2", "Information"},
    {"INFO_CRED", "Made by rhewrani"},
    {"MB_DEL_TTL", "Delete entry"},
    {"MB_DEL_CON", "Are you sure you want to delete this entry?"},
    {"MB_CLOS_TTL", "Close application"},
    {"MB_CLOS_CON", "There are unsaved changes. Would you like to save?\n\nIf discarded, all unsaved data since last save from %1 will be lost."},
    {"MB_CLOS_CON2", "There are unsaved changes. Would you like to save?\n\nIf discarded, all unsaved data will be lost."},
    {"MB_BU_TTL", "Load backup"},
    {"MB_BU_CON", "Are you sure you want to load this backup? All unsaved data since the last save from %1 will be lost."},
    {"MB_BU_CON2", "Are you sure you want to load this backup? All unsaved data will be lost."},
    {"MB_CLST_CON", "There are unsaved changes. Would you like to save?"},
    {"MB_CLST_CON2", "There are unsaved changes. Would you like to save? The program has to be restarted in order for it to function correctly."},
    {"MB_SAVE_TTL", "Save settings"},
    {"MB_SAVE_CON", "Are you sure you want to save these settings? The program has to be restarted in order for it to function correctly."},
    {"MB_ER_TTL", "Delete entries"},
    {"MB_ER_CON", "Are you sure you want to delete all entries?"},
    {"ERR_DATA_INVL", "Data validation failed!\n\nThe selected file does not have the correct format."},
};

// Deutsch
QMap<QString, QString> texts_de = {
    {"BTN_SAVE", "Speichern"},
    {"BTN_DIS", "Verwerfen"},
    {"BTN_CAN", "Abbrechen"},
    {"BTN_ADD", "Hinzufügen"},
    {"BTN_APP", "Anwenden"},
    {"BTN_RES", "Zurücksetzen"},
    {"BTN_YES", "Ja"},
    {"BTN_NO", "Nein"},
    {"TTL_INC", "EINKOMMENSLISTE"},
    {"TTL_EXP", "AUSGABENLISTE"},
    {"INC", "Einkommen"},
    {"EXP", "Ausgaben"},
    {"AM", "Betrag"},
    {"ITV", "Intervall"},
    {"DES", "Beschreibung"},
    {"CB_MTH", "Zeige nur monatlich an"},
    {"INC_SUM", "Summe Einnahmen:"},
    {"EXP_SUM", "Summe Ausgaben:"},
    {"PRF_SUM", "Summe insgesamt:"},
    {"MENU_MENU", "Menü"},
    {"MENU_DATA", "Datei"},
    {"MENU_ABOUT", "Über"},
    {"ACT_OPEN_SET", "Einstellungen öffnen..."},
    {"ACT_OPEN_CON", "Konfiguration öffnen..."},
    {"ACT_SAVE_ALL", "Alles speichern"},
    {"ACT_LOAD_BU", "Backup öffnen..."},
    {"ACT_ABOUT", "Über"},
    {"SW_TTL", "Einstellungen"},
    {"SW_LAN", "Sprache:"},
    {"SW_CUR", "Währung:"},
    {"SW_DAT", "Datumsformat:"},
    {"SW_DATA_FP", "Dateienpfad"},
    {"SW_DATA_TTL", "Datei öffnen..."},
    {"SW_CD", "Bestätigung bei Löschen"},
    {"SW_EAS", "Automatisches speichern"},
    {"SW_BOAE", "Backup bei Programmende"},
    {"SW_MXB", "Max. Backups:"},
    {"SW_ERASE", "Daten löschen"},
    {"SW_DT", "Entwicklertools"},
    {"SW_EL", "Logging"},
    {"SW_VER", "Anwendungsversion"},
    {"CW_EXP", "Ausgaben"},
    {"CW_INC", "Einnahmen"},
    {"CW_TTL", "Konfigurationsfenster"},
    {"CW_LAST_SAVE", "Letztes Speichern am"},
    {"EW_TTL","Eintragsfenster"},
    {"EW_SPBX_SUF"," Monate"},
    {"EW_CMBX_MTH","Monatlich"},
    {"EW_CMBX_QRT","Vierteljährlich"},
    {"EW_CMBX_YR","Jährlich"},
    {"EW_CMBX_ONT","Einmalig"},
    {"EW_CMBX_OTH","Andere"},
    {"EW_CMBX_OTH_TEXT","Jede %1 Monate"},
    {"EW_ADD_TO","Hinzufügen zu"},
    {"EW_EDIT","Hinzufügen zu"},
    {"EW_ERR_TTL","Ungültig!"},
    {"EW_ERR_ICR","Falsches Format"},
    {"EW_ERR_EMT","Eingabe darf nicht leer sein"},
    {"INFO_TTL", "Informationen über Finance Manager"},
    {"INFO_TTL2", "Informationen"},
    {"INFO_CRED", "Gemacht von rhewrani"},
    {"MB_DEL_TTL", "Eintrag löschen"},
    {"MB_DEL_CON", "Sind Sie sicher, dass Sie diesen Eintrag löschen wollen?"},
    {"MB_CLOS_TTL", "Anwendung schließen"},
    {"MB_CLOS_CON", "Es gibt ungespeicherte Änderungen. Möchten Sie speichern?\n\nWenn verworfen, gehen alle ungespeicherten Daten seit dem letzten Speichern vom %1 verloren."},
    {"MB_CLOS_CON2", "Es gibt ungespeicherte Änderungen. Möchten Sie speichern?\n\nWenn verworfen, gehen alle ungespeicherten Daten verloren."},
    {"MB_BU_TTL", "Backup laden"},
    {"MB_BU_CON", "Sind Sie sicher, dass Sie dieses Backup laden möchten? Alle ungespeicherten Daten seit dem letzten Speichern vom %1 gehen verloren."},
    {"MB_BU_CON2", "Sind Sie sicher, dass Sie dieses Backup laden möchten? Alle ungespeicherten Daten gehen verloren."},
    {"MB_CLST_CON", "Es gibt ungespeicherte Änderungen. Möchten Sie speichern?"},
    {"MB_CLST_CON2", "Es gibt ungespeicherte Änderungen. Möchten Sie speichern? Das Programm muss neu gestartet werden, damit es korrekt funktioniert."},
    {"MB_SAVE_TTL", "Einstellungen speichern"},
    {"MB_SAVE_CON", "Sind Sie sicher, dass Sie diese Einstellungen speichern möchten? Das Programm muss neu gestartet werden, damit es korrekt funktioniert."},
    {"MB_ER_TTL", "Einträge löschen"},
    {"MB_ER_CON", "Sind Sie sicher, dass Sie alle Einträge löschen wollen?"},
    {"ERR_DATA_INVL", "Datenvalidierung fehlgeschlagen!\n\nDie ausgewählte Datei hat nicht das richtige Format."},
    };

QMap<QString, QString> texts_nl = {
    {"BTN_SAVE", "Opslaan"},
    {"BTN_DIS", "Verwijderen"},
    {"BTN_CAN", "Annuleren"},
    {"BTN_ADD", "Toevoegen"},
    {"BTN_APP", "Toepassen"},
    {"BTN_RES", "Resetten"},
    {"BTN_YES", "Ja"},
    {"BTN_NO", "Nee"},
    {"TTL_INC", "INKOMSTENLIJST"},
    {"TTL_EXP", "UITGAVENLIJST"},
    {"INC", "Inkomen"},
    {"EXP", "Uitgaven"},
    {"AM", "Bedrag"},
    {"ITV", "Interval"},
    {"DES", "Beschrijving"},
    {"CB_MTH", "Toon alleen maandelijks"},
    {"INC_SUM", "Inkomenstotaal:"},
    {"EXP_SUM", "Uitgaventotaal:"},
    {"PRF_SUM", "Totaalbedrag:"},
    {"MENU_MENU", "Menu"},
    {"MENU_DATA", "Bestand"},
    {"MENU_ABOUT", "Over"},
    {"ACT_OPEN_SET", "Instellingen openen..."},
    {"ACT_OPEN_CON", "Configuratie openen..."},
    {"ACT_SAVE_ALL", "Alles opslaan"},
    {"ACT_LOAD_BU", "Back-up laden..."},
    {"ACT_ABOUT", "Over"},
    {"SW_TTL", "Instellingen"},
    {"SW_LAN", "Taal:"},
    {"SW_CUR", "Valuta:"},
    {"SW_DAT", "Datumnotatie:"},
    {"SW_DATA_FP", "Gegevensbestandspad"},
    {"SW_DATA_TTL", "Bestand openen..."},
    {"SW_CD", "Verwijderen bevestigen"},
    {"SW_EAS", "Automatisch opslaan"},
    {"SW_BOAE", "Back-up bij afsluiten"},
    {"SW_MXB", "Max. back-ups:"},
    {"SW_ERASE", "Gegevens wissen"},
    {"SW_DT", "Ontwikkelaarstools"},
    {"SW_EL", "Loggen"},
    {"SW_VER", "Applicatieversie"},
    {"CW_EXP", "Uitgaven"},
    {"CW_INC", "Inkomen"},
    {"CW_TTL", "Configuratievenster"},
    {"CW_LAST_SAVE", "Laatst opgeslagen op"},
    {"EW_TTL", "Invoervenster"},
    {"EW_SPBX_SUF", " maanden"},
    {"EW_CMBX_MTH", "Maandelijks"},
    {"EW_CMBX_QRT", "Driemaandelijks"},
    {"EW_CMBX_YR", "Jaarlijks"},
    {"EW_CMBX_ONT", "Eenmalig"},
    {"EW_CMBX_OTH", "Anders"},
    {"EW_CMBX_OTH_TEXT", "Elke %1 maanden"},
    {"EW_ADD_TO", "Toevoegen aan"},
    {"EW_EDIT", "Bewerken"},
    {"EW_ERR_TTL", "Ongeldig!"},
    {"EW_ERR_ICR", "Verkeerd formaat"},
    {"EW_ERR_EMT", "Invoer mag niet leeg zijn"},
    {"INFO_TTL", "Informatie over Finance Manager"},
    {"INFO_TTL2", "Informatie"},
    {"INFO_CRED", "Gemaakt door rhewrani"},
    {"MB_DEL_TTL", "Item verwijderen"},
    {"MB_DEL_CON", "Weet u zeker dat u dit item wilt verwijderen?"},
    {"MB_CLOS_TTL", "Applicatie sluiten"},
    {"MB_CLOS_CON", "Er zijn niet-opgeslagen wijzigingen. Wilt u deze opslaan?\n\nIndien verwijderd, gaan alle niet-opgeslagen gegevens sinds de laatste opslag van %1 verloren."},
    {"MB_CLOS_CON2", "Er zijn niet-opgeslagen wijzigingen. Wilt u deze opslaan?\n\nIndien verworpen, gaan alle niet-opgeslagen gegevens verloren."},
    {"MB_BU_TTL", "Back-up laden"},
    {"MB_BU_CON", "Weet u zeker dat u deze back-up wilt laden? Alle niet-opgeslagen gegevens sinds de laatste opslag van %1 gaan verloren."},
    {"MB_BU_CON2", "Weet u zeker dat u deze back-up wilt laden? Alle niet-opgeslagen gegevens gaan verloren."},
    {"MB_CLST_CON", "Er zijn niet-opgeslagen wijzigingen. Wilt u deze opslaan?"},
    {"MB_CLST_CON2", "Er zijn niet-opgeslagen wijzigingen. Wilt u deze opslaan? De applicatie moet opnieuw worden gestart om correct te functioneren."},
    {"MB_SAVE_TTL", "Instellingen opslaan"},
    {"MB_SAVE_CON", "Weet u zeker dat u deze instellingen wilt opslaan? De applicatie moet opnieuw worden gestart om correct te functioneren."},
    {"MB_ER_TTL", "Items verwijderen"},
    {"MB_ER_CON", "Weet u zeker dat u alle items wilt verwijderen?"},
    {"ERR_DATA_INVL", "Gegevensvalidatie mislukt!\n\nHet geselecteerde bestand heeft niet het juiste formaat."}
};

QMap<QString, QString> texts_fr = {
    {"BTN_SAVE", "Enregistrer"},
    {"BTN_DIS", "Supprimer"},
    {"BTN_CAN", "Annuler"},
    {"BTN_ADD", "Ajouter"},
    {"BTN_APP", "Appliquer"},
    {"BTN_RES", "Réinitialiser"},
    {"BTN_YES", "Oui"},
    {"BTN_NO", "Non"},
    {"TTL_INC", "LISTE DES REVENUS"},
    {"TTL_EXP", "LISTE DES DÉPENSES"},
    {"INC", "Revenus"},
    {"EXP", "Dépenses"},
    {"AM", "Montant"},
    {"ITV", "Intervalle"},
    {"DES", "Description"},
    {"CB_MTH", "Afficher uniquement mensuel"},
    {"INC_SUM", "Somme des revenus:"},
    {"EXP_SUM", "Somme des dépenses:"},
    {"PRF_SUM", "Somme totale:"},
    {"MENU_MENU", "Menu"},
    {"MENU_DATA", "Fichier"},
    {"MENU_ABOUT", "À propos"},
    {"ACT_OPEN_SET", "Ouvrir les paramètres..."},
    {"ACT_OPEN_CON", "Ouvrir la configuration..."},
    {"ACT_SAVE_ALL", "Tout enregistrer"},
    {"ACT_LOAD_BU", "Charger la sauvegarde..."},
    {"ACT_ABOUT", "À propos"},
    {"SW_TTL", "Paramètres"},
    {"SW_LAN", "Langue:"},
    {"SW_CUR", "Devise:"},
    {"SW_DAT", "Format de date:"},
    {"SW_DATA_FP", "Chemin du fichier de données"},
    {"SW_DATA_TTL", "Ouvrir un fichier..."},
    {"SW_CD", "Confirmer la suppression"},
    {"SW_EAS", "Sauvegarde automatique"},
    {"SW_BOAE", "Sauvegarde à la fermeture"},
    {"SW_MXB", "Sauvegardes max.:"},
    {"SW_ERASE", "Effacer les données"},
    {"SW_DT", "Outils développeur"},
    {"SW_EL", "Journalisation"},
    {"SW_VER", "Version de l'application"},
    {"CW_EXP", "Dépenses"},
    {"CW_INC", "Revenus"},
    {"CW_TTL", "Fenêtre de configuration"},
    {"CW_LAST_SAVE", "Dernière sauvegarde le"},
    {"EW_TTL", "Fenêtre de saisie"},
    {"EW_SPBX_SUF", " mois"},
    {"EW_CMBX_MTH", "Mensuel"},
    {"EW_CMBX_QRT", "Trimestriel"},
    {"EW_CMBX_YR", "Annuel"},
    {"EW_CMBX_ONT", "Ponctuel"},
    {"EW_CMBX_OTH", "Autre"},
    {"EW_CMBX_OTH_TEXT", "Tous les %1 mois"},
    {"EW_ADD_TO", "Ajouter à"},
    {"EW_EDIT", "Modifier"},
    {"EW_ERR_TTL", "Invalide !"},
    {"EW_ERR_ICR", "Format incorrect"},
    {"EW_ERR_EMT", "Le champ ne peut pas être vide"},
    {"INFO_TTL", "Informations sur Finance Manager"},
    {"INFO_TTL2", "Informations"},
    {"INFO_CRED", "Créé par rhewrani"},
    {"MB_DEL_TTL", "Supprimer l'élément"},
    {"MB_DEL_CON", "Êtes-vous sûr de vouloir supprimer cet élément?"},
    {"MB_CLOS_TTL", "Fermer l'application"},
    {"MB_CLOS_CON", "Il y a des modifications non enregistrées. Voulez-vous les enregistrer?\n\nSi vous les supprimez, toutes les données non enregistrées depuis la dernière sauvegarde du %1 seront perdues."},
    {"MB_CLOS_CON2", "Il y a des modifications non enregistrées. Voulez-vous les enregistrer?\n\nSi vous les supprimez, toutes les données non enregistrées seront perdues."},
    {"MB_BU_TTL", "Charger la sauvegarde"},
    {"MB_BU_CON", "Êtes-vous sûr de vouloir charger cette sauvegarde? Toutes les données non enregistrées depuis la dernière sauvegarde du %1 seront perdues."},
    {"MB_BU_CON2", "Êtes-vous sûr de vouloir charger cette sauvegarde? Toutes les données non enregistrées seront perdues."},
    {"MB_CLST_CON", "Il y a des modifications non enregistrées. Voulez-vous les enregistrer?"},
    {"MB_CLST_CON2", "Il y a des modifications non enregistrées. Voulez-vous les enregistrer? L'application doit être redémarrée pour fonctionner correctement."},
    {"MB_SAVE_TTL", "Enregistrer les paramètres"},
    {"MB_SAVE_CON", "Êtes-vous sûr de vouloir enregistrer ces paramètres? L'application doit être redémarrée pour fonctionner correctement."},
    {"MB_ER_TTL", "Supprimer les entrées"},
    {"MB_ER_CON", "Êtes-vous sûr de vouloir supprimer toutes les entrées?"},
    {"ERR_DATA_INVL", "Échec de la validation des données !\n\nLe fichier sélectionné n'a pas le bon format."}
};

QMap<QString, QString> texts_es = {
    {"BTN_SAVE", "Guardar"},
    {"BTN_DIS", "Descartar"},
    {"BTN_CAN", "Cancelar"},
    {"BTN_ADD", "Añadir"},
    {"BTN_APP", "Aplicar"},
    {"BTN_RES", "Reiniciar"},
    {"BTN_YES", "Sí"},
    {"BTN_NO", "No"},
    {"TTL_INC", "LISTA DE INGRESOS"},
    {"TTL_EXP", "LISTA DE GASTOS"},
    {"INC", "Ingresos"},
    {"EXP", "Gastos"},
    {"AM", "Cantidad"},
    {"ITV", "Intervalo"},
    {"DES", "Descripción"},
    {"CB_MTH", "Mostrar solo mensual"},
    {"INC_SUM", "Total ingresos:"},
    {"EXP_SUM", "Total gastos:"},
    {"PRF_SUM", "Total general:"},
    {"MENU_MENU", "Menú"},
    {"MENU_DATA", "Archivo"},
    {"MENU_ABOUT", "Acerca de"},
    {"ACT_OPEN_SET", "Abrir ajustes..."},
    {"ACT_OPEN_CON", "Abrir configuración..."},
    {"ACT_SAVE_ALL", "Guardar todo"},
    {"ACT_LOAD_BU", "Cargar copia..."},
    {"ACT_ABOUT", "Acerca de"},
    {"SW_TTL", "Ajustes"},
    {"SW_LAN", "Idioma:"},
    {"SW_CUR", "Moneda:"},
    {"SW_DAT", "Formato fecha:"},
    {"SW_DATA_FP", "Ruta datos:"},
    {"SW_DATA_TTL", "Abrir archivo..."},
    {"SW_CD", "Confirmar borrado"},
    {"SW_EAS", "Guardado automático"},
    {"SW_BOAE", "Copia al salir"},
    {"SW_MXB", "Copias máx.:"},
    {"SW_ERASE", "Borrar datos"},
    {"SW_DT", "Herramientas"},
    {"SW_EL", "Registro"},
    {"SW_VER", "Versión:"},
    {"CW_EXP", "Gastos"},
    {"CW_INC", "Ingresos"},
    {"CW_TTL", "Configuración"},
    {"CW_LAST_SAVE", "Último guardado:"},
    {"EW_TTL", "Ventana entrada"},
    {"EW_SPBX_SUF", " meses"},
    {"EW_CMBX_MTH", "Mensual"},
    {"EW_CMBX_QRT", "Trimestral"},
    {"EW_CMBX_YR", "Anual"},
    {"EW_CMBX_ONT", "Único"},
    {"EW_CMBX_OTH", "Otro"},
    {"EW_CMBX_OTH_TEXT", "Cada %1 meses"},
    {"EW_ADD_TO", "Añadir a"},
    {"EW_EDIT", "Editar"},
    {"EW_ERR_TTL", "¡Inválido!"},
    {"EW_ERR_ICR", "Formato incorrecto"},
    {"EW_ERR_EMT", "Campo obligatorio"},
    {"INFO_TTL", "Acerca de Finance Manager"},
    {"INFO_TTL2", "Información"},
    {"INFO_CRED", "Creado por rhewrani"},
    {"MB_DEL_TTL", "Borrar elemento"},
    {"MB_DEL_CON", "¿Seguro que quieres borrar este elemento?"},
    {"MB_CLOS_TTL", "Cerrar aplicación"},
    {"MB_CLOS_CON", "Hay cambios sin guardar. ¿Guardar?\n\nSi se descartan, se perderán los datos desde la última copia de seguridad del %1."},
    {"MB_CLOS_CON2", "Hay cambios sin guardar. ¿Guardar?\n\nSi se descartan, se perderán todos los datos sin guardar."},
    {"MB_BU_TTL", "Cargar copia"},
    {"MB_BU_CON", "¿Seguro que quieres cargar esta copia? Se perderán los datos desde la última copia de seguridad del %1."},
    {"MB_BU_CON2", "¿Seguro que quieres cargar esta copia de seguridad? Se perderán todos los datos sin guardar."},
    {"MB_CLST_CON", "Hay cambios sin guardar. ¿Guardar?"},
    {"MB_CLST_CON2", "Hay cambios sin guardar. ¿Guardar? La aplicación debe reiniciarse para funcionar correctamente."},
    {"MB_SAVE_TTL", "Guardar ajustes"},
    {"MB_SAVE_CON", "¿Seguro que quieres guardar estos ajustes? La aplicación debe reiniciarse para funcionar correctamente."},
    {"MB_ER_TTL", "Borrar entradas"},
    {"MB_ER_CON", "¿Seguro que quieres borrar todas las entradas?"},
    {"ERR_DATA_INVL", "¡Error de validación!\n\nEl archivo no tiene el formato correcto."}
};

QMap<QString, QString> texts_it = {
    {"BTN_SAVE", "Salva"},
    {"BTN_DIS", "Scarta"},
    {"BTN_CAN", "Annulla"},
    {"BTN_ADD", "Aggiungi"},
    {"BTN_APP", "Applica"},
    {"BTN_RES", "Reimposta"},
    {"BTN_YES", "Sì"},
    {"BTN_NO", "No"},
    {"TTL_INC", "ELENCO ENTRATE"},
    {"TTL_EXP", "ELENCO USCITE"},
    {"INC", "Entrate"},
    {"EXP", "Uscite"},
    {"AM", "Importo"},
    {"ITV", "Intervallo"},
    {"DES", "Descrizione"},
    {"CB_MTH", "Mostra solo mensile"},
    {"INC_SUM", "Totale entrate:"},
    {"EXP_SUM", "Totale uscite:"},
    {"PRF_SUM", "Totale generale:"},
    {"MENU_MENU", "Menu"},
    {"MENU_DATA", "File"},
    {"MENU_ABOUT", "Informazioni"},
    {"ACT_OPEN_SET", "Apri impostazioni..."},
    {"ACT_OPEN_CON", "Apri configurazione..."},
    {"ACT_SAVE_ALL", "Salva tutto"},
    {"ACT_LOAD_BU", "Carica backup..."},
    {"ACT_ABOUT", "Informazioni"},
    {"SW_TTL", "Impostazioni"},
    {"SW_LAN", "Lingua:"},
    {"SW_CUR", "Valuta:"},
    {"SW_DAT", "Formato data:"},
    {"SW_DATA_FP", "Percorso dati:"},
    {"SW_DATA_TTL", "Apri file..."},
    {"SW_CD", "Conferma eliminazione"},
    {"SW_EAS", "Salvataggio automatico"},
    {"SW_BOAE", "Backup alla chiusura"},
    {"SW_MXB", "Backup massimi:"},
    {"SW_ERASE", "Cancella dati"},
    {"SW_DT", "Strumenti sviluppo"},
    {"SW_EL", "Registrazione"},
    {"SW_VER", "Versione:"},
    {"CW_EXP", "Uscite"},
    {"CW_INC", "Entrate"},
    {"CW_TTL", "Configurazione"},
    {"CW_LAST_SAVE", "Ultimo salvataggio:"},
    {"EW_TTL", "Finestra inserimento"},
    {"EW_SPBX_SUF", " mesi"},
    {"EW_CMBX_MTH", "Mensile"},
    {"EW_CMBX_QRT", "Trimestrale"},
    {"EW_CMBX_YR", "Annuale"},
    {"EW_CMBX_ONT", "Una tantum"},
    {"EW_CMBX_OTH", "Altro"},
    {"EW_CMBX_OTH_TEXT", "Ogni %1 mesi"},
    {"EW_ADD_TO", "Aggiungi a"},
    {"EW_EDIT", "Modifica"},
    {"EW_ERR_TTL", "Non valido!"},
    {"EW_ERR_ICR", "Formato errato"},
    {"EW_ERR_EMT", "Campo obbligatorio"},
    {"INFO_TTL", "Informazioni su Finance Manager"},
    {"INFO_TTL2", "Informazioni"},
    {"INFO_CRED", "Creato da rhewrani"},
    {"MB_DEL_TTL", "Elimina elemento"},
    {"MB_DEL_CON", "Sei sicuro di voler eliminare questo elemento?"},
    {"MB_CLOS_TTL", "Chiudi applicazione"},
    {"MB_CLOS_CON", "Ci sono modifiche non salvate. Salvare?\n\nSe scartate, andranno perse le modifiche dall'ultimo salvataggio del %1."},
    {"MB_CLOS_CON2", "Ci sono modifiche non salvate. Salvare?\n\nSe scartate, andranno perse tutte le modifiche non salvate."},
    {"MB_BU_TTL", "Carica backup"},
    {"MB_BU_CON", "Sei sicuro di voler caricare questo backup? Andranno perse le modifiche dall'ultimo salvataggio del %1."},
    {"MB_BU_CON2", "Sei sicuro di voler caricare questo backup? Andranno perse tutte le modifiche non salvate."},
    {"MB_CLST_CON", "Ci sono modifiche non salvate. Salvare?"},
    {"MB_CLST_CON2", "Ci sono modifiche non salvate. Salvare? L'applicazione deve essere riavviata per funzionare correttamente."},
    {"MB_SAVE_TTL", "Salva impostazioni"},
    {"MB_SAVE_CON", "Sei sicuro di voler salvare queste impostazioni? L'applicazione deve essere riavviata per funzionare correttamente."},
    {"MB_ER_TTL", "Elimina voci"},
    {"MB_ER_CON", "Sei sicuro di voler eliminare tutte le voci?"},
    {"ERR_DATA_INVL", "Errore di validazione!\n\nIl file non ha il formato corretto."}
};

QMap<QString, QString> texts_zh = {
    {"BTN_SAVE", "保存"},
    {"BTN_DIS", "丢弃"},
    {"BTN_CAN", "取消"},
    {"BTN_ADD", "添加"},
    {"BTN_APP", "应用"},
    {"BTN_RES", "重置"},
    {"BTN_YES", "是"},
    {"BTN_NO", "否"},
    {"TTL_INC", "收入列表"},
    {"TTL_EXP", "支出列表"},
    {"INC", "收入"},
    {"EXP", "支出"},
    {"AM", "金额"},
    {"ITV", "间隔"},
    {"DES", "描述"},
    {"CB_MTH", "仅显示月度"},
    {"INC_SUM", "收入总计:"},
    {"EXP_SUM", "支出总计:"},
    {"PRF_SUM", "总和:"},
    {"MENU_MENU", "菜单"},
    {"MENU_DATA", "文件"},
    {"MENU_ABOUT", "关于"},
    {"ACT_OPEN_SET", "打开设置..."},
    {"ACT_OPEN_CON", "打开配置..."},
    {"ACT_SAVE_ALL", "全部保存"},
    {"ACT_LOAD_BU", "加载备份..."},
    {"ACT_ABOUT", "关于"},
    {"SW_TTL", "设置"},
    {"SW_LAN", "语言:"},
    {"SW_CUR", "货币:"},
    {"SW_DAT", "日期格式:"},
    {"SW_DATA_FP", "数据路径:"},
    {"SW_DATA_TTL", "打开文件..."},
    {"SW_CD", "确认删除"},
    {"SW_EAS", "自动保存"},
    {"SW_BOAE", "退出时备份"},
    {"SW_MXB", "最大备份数:"},
    {"SW_ERASE", "清除数据"},
    {"SW_DT", "开发者工具"},
    {"SW_EL", "日志"},
    {"SW_VER", "版本:"},
    {"CW_EXP", "支出"},
    {"CW_INC", "收入"},
    {"CW_TTL", "配置窗口"},
    {"CW_LAST_SAVE", "最后保存:"},
    {"EW_TTL", "条目窗口"},
    {"EW_SPBX_SUF", " 个月"},
    {"EW_CMBX_MTH", "每月"},
    {"EW_CMBX_QRT", "每季"},
    {"EW_CMBX_YR", "每年"},
    {"EW_CMBX_ONT", "一次性"},
    {"EW_CMBX_OTH", "其他"},
    {"EW_CMBX_OTH_TEXT", "每%1个月"},
    {"EW_ADD_TO", "添加到"},
    {"EW_EDIT", "编辑"},
    {"EW_ERR_TTL", "无效!"},
    {"EW_ERR_ICR", "格式错误"},
    {"EW_ERR_EMT", "不能为空"},
    {"INFO_TTL", "关于财务管理器"},
    {"INFO_TTL2", "信息"},
    {"INFO_CRED", "由rhewrani制作"},
    {"MB_DEL_TTL", "删除条目"},
    {"MB_DEL_CON", "确定要删除此条目吗?"},
    {"MB_CLOS_TTL", "关闭程序"},
    {"MB_CLOS_CON", "有未保存的更改。是否保存?\n\n如果丢弃,将丢失自%1以来的所有未保存数据。"},
    {"MB_CLOS_CON2", "有未保存的更改。是否保存?\n\n如果丢弃,所有未保存的数据将丢失。"},
    {"MB_BU_TTL", "加载备份"},
    {"MB_BU_CON", "确定要加载此备份吗?将丢失自%1以来的所有未保存数据。"},
    {"MB_BU_CON2", "确定要加载此备份吗?所有未保存的数据将丢失。"},
    {"MB_CLST_CON", "有未保存的更改。是否保存?"},
    {"MB_CLST_CON2", "有未保存的更改。是否保存?程序需要重启才能正常运行。"},
    {"MB_SAVE_TTL", "保存设置"},
    {"MB_SAVE_CON", "确定要保存这些设置吗?程序需要重启才能正常运行。"},
    {"MB_ER_TTL", "删除条目"},
    {"MB_ER_CON", "确定要删除所有条目吗?"},
    {"ERR_DATA_INVL", "数据验证失败!\n\n所选文件格式不正确。"}
};

QMap<QString, QString> texts_jp = {
    {"BTN_SAVE", "保存"},
    {"BTN_DIS", "破棄"},
    {"BTN_CAN", "キャンセル"},
    {"BTN_ADD", "追加"},
    {"BTN_APP", "適用"},
    {"BTN_RES", "リセット"},
    {"BTN_YES", "はい"},
    {"BTN_NO", "いいえ"},
    {"TTL_INC", "収入リスト"},
    {"TTL_EXP", "支出リスト"},
    {"INC", "収入"},
    {"EXP", "支出"},
    {"AM", "金額"},
    {"ITV", "間隔"},
    {"DES", "説明"},
    {"CB_MTH", "月次のみ表示"},
    {"INC_SUM", "収入合計:"},
    {"EXP_SUM", "支出合計:"},
    {"PRF_SUM", "合計:"},
    {"MENU_MENU", "メニュー"},
    {"MENU_DATA", "ファイル"},
    {"MENU_ABOUT", "情報"},
    {"ACT_OPEN_SET", "設定を開く..."},
    {"ACT_OPEN_CON", "設定を開く..."},
    {"ACT_SAVE_ALL", "すべて保存"},
    {"ACT_LOAD_BU", "バックアップ読み込み..."},
    {"ACT_ABOUT", "情報"},
    {"SW_TTL", "設定"},
    {"SW_LAN", "言語:"},
    {"SW_CUR", "通貨:"},
    {"SW_DAT", "日付形式:"},
    {"SW_DATA_FP", "データパス:"},
    {"SW_DATA_TTL", "ファイルを開く..."},
    {"SW_CD", "削除確認"},
    {"SW_EAS", "自動保存"},
    {"SW_BOAE", "終了時バックアップ"},
    {"SW_MXB", "最大バックアップ数:"},
    {"SW_ERASE", "データ消去"},
    {"SW_DT", "開発者ツール"},
    {"SW_EL", "ログ"},
    {"SW_VER", "バージョン:"},
    {"CW_EXP", "支出"},
    {"CW_INC", "収入"},
    {"CW_TTL", "設定ウィンドウ"},
    {"CW_LAST_SAVE", "最終保存:"},
    {"EW_TTL", "エントリウィンドウ"},
    {"EW_SPBX_SUF", " ヶ月"},
    {"EW_CMBX_MTH", "毎月"},
    {"EW_CMBX_QRT", "四半期"},
    {"EW_CMBX_YR", "年次"},
    {"EW_CMBX_ONT", "一回のみ"},
    {"EW_CMBX_OTH", "その他"},
    {"EW_CMBX_OTH_TEXT", "%1ヶ月毎"},
    {"EW_ADD_TO", "追加先"},
    {"EW_EDIT", "編集"},
    {"EW_ERR_TTL", "無効!"},
    {"EW_ERR_ICR", "形式エラー"},
    {"EW_ERR_EMT", "必須項目"},
    {"INFO_TTL", "ファイナンスマネージャーについて"},
    {"INFO_TTL2", "情報"},
    {"INFO_CRED", "rhewrani作成"},
    {"MB_DEL_TTL", "エントリ削除"},
    {"MB_DEL_CON", "このエントリを削除してもよろしいですか?"},
    {"MB_CLOS_TTL", "アプリ終了"},
    {"MB_CLOS_CON", "未保存の変更があります。保存しますか?\n\n破棄すると、%1以降の未保存データは失われます。"},
    {"MB_CLOS_CON2", "未保存の変更があります。保存しますか?\n\n破棄すると、すべての未保存データは失われます。"},
    {"MB_BU_TTL", "バックアップ読み込み"},
    {"MB_BU_CON", "このバックアップを読み込みますか?%1以降の未保存データは失われます。"},
    {"MB_BU_CON2", "このバックアップを読み込みますか?すべての未保存データは失われます。"},
    {"MB_CLST_CON", "未保存の変更があります。保存しますか?"},
    {"MB_CLST_CON2", "未保存の変更があります。保存しますか?プログラムを再起動する必要があります。"},
    {"MB_SAVE_TTL", "設定保存"},
    {"MB_SAVE_CON", "これらの設定を保存しますか?プログラムを再起動する必要があります。"},
    {"MB_ER_TTL", "エントリ削除"},
    {"MB_ER_CON", "すべてのエントリを削除してもよろしいですか?"},
    {"ERR_DATA_INVL", "データ検証失敗!\n\n選択したファイルの形式が正しくありません。"}
};

QMap<QString, QString> texts_kr = {
    {"BTN_SAVE", "저장"},
    {"BTN_DIS", "버리기"},
    {"BTN_CAN", "취소"},
    {"BTN_ADD", "추가"},
    {"BTN_APP", "적용"},
    {"BTN_RES", "재설정"},
    {"BTN_YES", "예"},
    {"BTN_NO", "아니오"},
    {"TTL_INC", "수입 목록"},
    {"TTL_EXP", "지출 목록"},
    {"INC", "수입"},
    {"EXP", "지출"},
    {"AM", "금액"},
    {"ITV", "간격"},
    {"DES", "설명"},
    {"CB_MTH", "월간만 표시"},
    {"INC_SUM", "수입 합계:"},
    {"EXP_SUM", "지출 합계:"},
    {"PRF_SUM", "총 합계:"},
    {"MENU_MENU", "메뉴"},
    {"MENU_DATA", "파일"},
    {"MENU_ABOUT", "정보"},
    {"ACT_OPEN_SET", "설정 열기..."},
    {"ACT_OPEN_CON", "구성 열기..."},
    {"ACT_SAVE_ALL", "모두 저장"},
    {"ACT_LOAD_BU", "백업 불러오기..."},
    {"ACT_ABOUT", "정보"},
    {"SW_TTL", "설정"},
    {"SW_LAN", "언어:"},
    {"SW_CUR", "통화:"},
    {"SW_DAT", "날짜 형식:"},
    {"SW_DATA_FP", "데이터 경로:"},
    {"SW_DATA_TTL", "파일 열기..."},
    {"SW_CD", "삭제 확인"},
    {"SW_EAS", "자동 저장"},
    {"SW_BOAE", "종료 시 백업"},
    {"SW_MXB", "최대 백업:"},
    {"SW_ERASE", "데이터 삭제"},
    {"SW_DT", "개발자 도구"},
    {"SW_EL", "로그"},
    {"SW_VER", "버전:"},
    {"CW_EXP", "지출"},
    {"CW_INC", "수입"},
    {"CW_TTL", "설정 창"},
    {"CW_LAST_SAVE", "마지막 저장:"},
    {"EW_TTL", "항목 창"},
    {"EW_SPBX_SUF", " 개월"},
    {"EW_CMBX_MTH", "월간"},
    {"EW_CMBX_QRT", "분기별"},
    {"EW_CMBX_YR", "연간"},
    {"EW_CMBX_ONT", "한 번만"},
    {"EW_CMBX_OTH", "기타"},
    {"EW_CMBX_OTH_TEXT", "%1개월마다"},
    {"EW_ADD_TO", "추가 대상"},
    {"EW_EDIT", "편집"},
    {"EW_ERR_TTL", "잘못됨!"},
    {"EW_ERR_ICR", "형식 오류"},
    {"EW_ERR_EMT", "필수 입력"},
    {"INFO_TTL", "파이낸스 매니저 정보"},
    {"INFO_TTL2", "정보"},
    {"INFO_CRED", "rhewrani 제작"},
    {"MB_DEL_TTL", "항목 삭제"},
    {"MB_DEL_CON", "이 항목을 삭제하시겠습니까?"},
    {"MB_CLOS_TTL", "앱 종료"},
    {"MB_CLOS_CON", "저장되지 않은 변경사항이 있습니다. 저장하시겠습니까?\n\n버리면 %1 이후의 저장되지 않은 데이터가 손실됩니다."},
    {"MB_CLOS_CON2", "저장되지 않은 변경사항이 있습니다. 저장하시겠습니까?\n\n버리면 모든 저장되지 않은 데이터가 손실됩니다."},
    {"MB_BU_TTL", "백업 불러오기"},
    {"MB_BU_CON", "이 백업을 불러오시겠습니까? %1 이후의 저장되지 않은 데이터가 손실됩니다."},
    {"MB_BU_CON2", "이 백업을 불러오시겠습니까? 모든 저장되지 않은 데이터가 손실됩니다."},
    {"MB_CLST_CON", "저장되지 않은 변경사항이 있습니다. 저장하시겠습니까?"},
    {"MB_CLST_CON2", "저장되지 않은 변경사항이 있습니다. 저장하시겠습니까? 프로그램을 재시작해야 합니다."},
    {"MB_SAVE_TTL", "설정 저장"},
    {"MB_SAVE_CON", "이 설정을 저장하시겠습니까? 프로그램을 재시작해야 합니다."},
    {"MB_ER_TTL", "항목 삭제"},
    {"MB_ER_CON", "모든 항목을 삭제하시겠습니까?"},
    {"ERR_DATA_INVL", "데이터 검증 실패!\n\n선택한 파일의 형식이 올바르지 않습니다."}
};

QMap<QString, QString> texts_ar = {
    {"BTN_SAVE", "حفظ"},
    {"BTN_DIS", "تجاهل"},
    {"BTN_CAN", "إلغاء"},
    {"BTN_ADD", "إضافة"},
    {"BTN_APP", "تطبيق"},
    {"BTN_RES", "إعادة تعيين"},
    {"BTN_YES", "نعم"},
    {"BTN_NO", "لا"},
    {"TTL_INC", "قائمة الدخل"},
    {"TTL_EXP", "قائمة المصروفات"},
    {"INC", "الدخل"},
    {"EXP", "المصروفات"},
    {"AM", "المبلغ"},
    {"ITV", "الفترة"},
    {"DES", "الوصف"},
    {"CB_MTH", "عرض الشهري فقط"},
    {"INC_SUM", "مجموع الدخل:"},
    {"EXP_SUM", "مجموع المصروفات:"},
    {"PRF_SUM", "المجموع الكلي:"},
    {"MENU_MENU", "القائمة"},
    {"MENU_DATA", "ملف"},
    {"MENU_ABOUT", "حول"},
    {"ACT_OPEN_SET", "فتح الإعدادات..."},
    {"ACT_OPEN_CON", "فتح التكوين..."},
    {"ACT_SAVE_ALL", "حفظ الكل"},
    {"ACT_LOAD_BU", "تحميل النسخة الاحتياطية..."},
    {"ACT_ABOUT", "حول"},
    {"SW_TTL", "الإعدادات"},
    {"SW_LAN", "اللغة:"},
    {"SW_CUR", "العملة:"},
    {"SW_DAT", "تنسيق التاريخ:"},
    {"SW_DATA_FP", "مسار البيانات:"},
    {"SW_DATA_TTL", "فتح ملف..."},
    {"SW_CD", "تأكيد الحذف"},
    {"SW_EAS", "حفظ تلقائي"},
    {"SW_BOAE", "نسخ احتياطي عند الخروج"},
    {"SW_MXB", "أقصى نسخ احتياطية:"},
    {"SW_ERASE", "محو البيانات"},
    {"SW_DT", "أدوات المطور"},
    {"SW_EL", "السجل"},
    {"SW_VER", "الإصدار:"},
    {"CW_EXP", "المصروفات"},
    {"CW_INC", "الدخل"},
    {"CW_TTL", "نافذة التكوين"},
    {"CW_LAST_SAVE", "آخر حفظ:"},
    {"EW_TTL", "نافذة الإدخال"},
    {"EW_SPBX_SUF", " أشهر"},
    {"EW_CMBX_MTH", "شهري"},
    {"EW_CMBX_QRT", "ربع سنوي"},
    {"EW_CMBX_YR", "سنوي"},
    {"EW_CMBX_ONT", "مرة واحدة"},
    {"EW_CMBX_OTH", "آخر"},
    {"EW_CMBX_OTH_TEXT", "كل %1 أشهر"},
    {"EW_ADD_TO", "إضافة إلى"},
    {"EW_EDIT", "تحرير"},
    {"EW_ERR_TTL", "غير صالح!"},
    {"EW_ERR_ICR", "تنسيق خاطئ"},
    {"EW_ERR_EMT", "الحقل مطلوب"},
    {"INFO_TTL", "حول مدير المالية"},
    {"INFO_TTL2", "معلومات"},
    {"INFO_CRED", "صنع بواسطة rhewrani"},
    {"MB_DEL_TTL", "حذف العنصر"},
    {"MB_DEL_CON", "هل أنت متأكد من حذف هذا العنصر؟"},
    {"MB_CLOS_TTL", "إغلاق التطبيق"},
    {"MB_CLOS_CON", "هناك تغييرات غير محفوظة. هل تريد الحفظ؟\n\nإذا تم تجاهلها، ستفقد جميع البيانات غير المحفوظة منذ آخر حفظ في %1."},
    {"MB_CLOS_CON2", "هناك تغييرات غير محفوظة. هل تريد الحفظ؟\n\nإذا تم تجاهلها، ستفقد جميع البيانات غير المحفوظة."},
    {"MB_BU_TTL", "تحميل النسخة الاحتياطية"},
    {"MB_BU_CON", "هل أنت متأكد من تحميل هذه النسخة الاحتياطية؟ ستفقد جميع البيانات غير المحفوظة منذ آخر حفظ في %1."},
    {"MB_BU_CON2", "هل أنت متأكد من تحميل هذا النسخة الاحتياطية؟ ستفقد جميع البيانات غير المحفوظة."},
    {"MB_CLST_CON", "هناك تغييرات غير محفوظة. هل تريد الحفظ؟"},
    {"MB_CLST_CON2", "هناك تغييرات غير محفوظة. هل تريد الحفظ؟ يجب إعادة تشغيل التطبيق ليعمل بشكل صحيح."},
    {"MB_SAVE_TTL", "حفظ الإعدادات"},
    {"MB_SAVE_CON", "هل أنت متأكد من حفظ هذه الإعدادات؟ يجب إعادة تشغيل التطبيق ليعمل بشكل صحيح."},
    {"MB_ER_TTL", "حذف الإدخالات"},
    {"MB_ER_CON", "هل أنت متأكد من حذف جميع الإدخالات؟"},
    {"ERR_DATA_INVL", "فشل التحقق من صحة البيانات!\n\nالملف المحدد ليس بالتنسيق الصحيح."}
};
